# -*- coding: utf-8 -*-
from __future__ import print_function, unicode_literals, division, absolute_import

p2p_groups = {
    'CHD',
    'CRiSC',
    'CtrlHD',
    'D-Z0N3',
    'de[42]',
    'decibeL',
    'DiRTY',
    'DON',
    'EA',
    'EbP',
    'ECI',
    'ESiR',
    'EuReKa',
    'FoRM',
    'FraMeSToR',
    'FTW-HD',
    'fty',
    'H@M',
    'h264iRMU',
    'HaB',
    'HDC',
    'HDCLUB',
    'HDEncX',
    'HDMaNiAcS',
    'HiDt',
    'iLL',
    'MCR',
    'MySiLU',
    'PerfectionHD',
    'RuDE',
    'THORA',
    'ViSTA™',
    'WiKi',
    'wsp®',
    'xander',
    'XTSF',
}